import assert from 'node:assert/strict';
import { test } from 'node:test';
import { artwork, authorized, digest, validate } from './server.mjs';

const valid = { event_id: 42, idempotency_key: 'culf-event-42', name: 'Festival Moment', symbol: 'CULF42', event_title: 'A major cultural festival begins', event_slug: 'japan-cultural-festival', summary: 'A public festival is drawing attention across Japan and international news outlets.', region: 'Japan', category: 'festival', evidence: [] };

test('service authentication compares bearer tokens and rejects missing credentials', () => {
  assert.equal(authorized('Bearer test-token', 'test-token'), true);
  assert.equal(authorized('Bearer wrong-token', 'test-token'), false);
  assert.equal(authorized(undefined, 'test-token'), false);
});

test('artwork is generated by Culf and safely escapes event text', () => {
  const svg = artwork('<Festival & Friends>', 'Japan');
  assert.match(svg, /ORIGINAL CULF ARTWORK/);
  assert.match(svg, /&lt;Festival &amp; Friends&gt;/);
  assert.doesNotMatch(svg, /<Festival & Friends>/);
});

test('launch package validation enforces required fields and token field lengths', () => {
  assert.doesNotThrow(() => validate(valid));
  assert.throws(() => validate({ ...valid, symbol: 'SYMBOLTOOLONG123' }), /exceeds limits/);
  assert.throws(() => validate({ ...valid, event_id: 0 }), /Invalid event_id/);
  assert.throws(() => validate({ ...valid, summary: '' }), /Missing summary/);
});

test('content hashes are stable for idempotent requests', () => {
  const first = digest(JSON.stringify(valid));
  assert.equal(digest(JSON.stringify(valid)), first);
  assert.notEqual(digest(JSON.stringify({ ...valid, symbol: 'CULF43' })), first);
});
